### ISSUE TITLE
lowz not defined when i run this code.

### ISSUE THREAD

**Issue by lehdkfjkdt** [Bharath2/iLQR#3]
https://github.com/Bharath2/iLQR/blob/b79a198ce2c7417e44b3da223aa345c2d5800bf6/ilqr/utils.py#L42

**Comment by bharadwajch123** [comment]
it is a typo, please correct it

**Comment by Bharath2** [comment]
Thanks again

**Comment by Bharath2** [comment]
Feel free to contribute to the repo
